// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final apiKey = dotenv.env['API_KEY'];
  static final appId = dotenv.env['APP_ID'];
  static final messagingSenderId = dotenv.env['MESSAGING_SENDER_ID'];
  static final projectId = dotenv.env['PROJECT_ID'];
  static final authDomain = dotenv.env['AUTH_DOMAIN'];
  static final storageBucket = dotenv.env['STORAGE_BUCKET'];

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: apiKey.toString(),
    appId: appId.toString(),
    messagingSenderId: messagingSenderId.toString(),
    projectId: projectId.toString(),
    authDomain: authDomain.toString(),
    storageBucket: storageBucket.toString(),
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: apiKey.toString(),
    appId: appId.toString(),
    messagingSenderId: messagingSenderId.toString(),
    projectId: projectId.toString(),
    storageBucket: storageBucket.toString(),
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: apiKey.toString(),
    appId: appId.toString(),
    messagingSenderId: messagingSenderId.toString(),
    projectId: projectId.toString(),
    storageBucket: storageBucket.toString(),
    iosBundleId: 'com.example.personalPortfolio',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: apiKey.toString(),
    appId: appId.toString(),
    messagingSenderId: messagingSenderId.toString(),
    projectId: projectId.toString(),
    storageBucket: storageBucket.toString(),
    iosBundleId: 'com.example.personalPortfolio',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: apiKey.toString(),
    appId: appId.toString(),
    messagingSenderId: messagingSenderId.toString(),
    projectId: projectId.toString(),
    authDomain: authDomain.toString(),
    storageBucket: storageBucket.toString(),
  );
}
